#!/bin/sh

cd ~/icfp-2016

mkdir -p log
(
  flock -n 9 || exit 1
  (
    ./get_snapshots
    ./get_problems

    for p in `ls data/problems`; do
      ./make_fc2 $p || ./make_fc $p
    done

    ./submit_solutions
    ./submit_problems
  ) 2>&1 | tee -a log/cron_target.log
) 9>>log/cron_target.log
