#!/bin/bash

KEY=`cat key`

ID=$1

[ -e data/problems/$ID/solved -o -e data/problems/$ID/solutions/fc/solution.txt ] && exit 0
mkdir -p data/problems/$ID/solutions/fc

echo `date -Iseconds`": Generating solution fc for problem $ID"
java -classpath /home/popiel/icfp-2016/target/scala-2.10/classes:/home/popiel/.sbt/boot/scala-2.10.6/lib/scala-library.jar:/home/popiel/.ivy2/cache/org.scalactic/scalactic_2.10/bundles/scalactic_2.10-3.0.0.jar:/home/popiel/.sbt/boot/scala-2.10.6/lib/scala-reflect.jar com.wolfskeep.icfp2016.FlatCentroid < data/problems/$ID/spec.txt > data/problems/$ID/solutions/fc/solution.txt
# sbt -no-colors --error "set showSuccess := false" "run-main com.wolfskeep.icfp2016.FlatCentroid" < data/problems/$ID/spec.txt > data/problems/$ID/solutions/fc/solution.txt

if grep '^\[' data/problems/$ID/solutions/fc/solution.txt; then
  rm data/problems/$ID/solutions/fc/*
fi
