#!/bin/bash

KEY=`cat key`

for ID in `ls data/problems`; do
  for solution in `ls data/problems/$ID/solutions`; do
    if [ ! -e data/problems/$ID/solved -a ! -e data/problems/$ID/solutions/$solution/result.json ]; then
      echo "Submitting problem $ID solution $solution"
      curl --compressed -L -H Expect: -H "X-API-Key: $KEY" -F "problem_id=$ID" -F "solution_spec=@data/problems/$ID/solutions/$solution/solution.txt" 'http://2016sv.icfpcontest.org/api/solution/submit' > data/problems/$ID/solutions/$solution/result.json
      sleep 1
    fi
    if jq -r .resemblance data/problems/$ID/solutions/$solution/result.json | perl -e '$num = <> + 0.0; exit($num != 1.0);'; then
      echo Problem $ID SOLVED with $solution
      touch data/problems/$ID/solved
    fi
  done
done
